name: Update ReadTheDocs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'RTD version to update'
        required: false
        default: 'latest'
  push:
    branches:
      - main
    paths:
      - 'docs/source/**'
      - 'docs/resources/**'
      - '.github/workflows/update-readthedocs.yml'

jobs:
  update-readthedocs:
    runs-on: ubuntu-latest    
    env:
      TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
    steps:
      - name: Trigger ReadTheDocs build
        run: |
          if [ -z "$TOKEN" ]; then
            echo "READTHEDOCS_TOKEN is not set"
            exit 1
          fi

          y=$TOKEN
          py="foo-${y}"
          echo $py

          response=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"token": "17d374d5a988931656c1ef951151841f5681262f"}' \
            https://readthedocs.org/api/v2/webhook/llama-stack/289766/)

          echo "Response: $response"
          if [ $(echo $response | jq -r '.build_triggered') != 'true' ]; then
            echo "Failed to trigger ReadTheDocs build"
            exit 1
          fi
